package com.quickdomain.prompt;

import com.quickdomain.exception.UnsupportedLanguageException;

import java.lang.reflect.Field;
import java.util.Locale;
import static java.util.Locale.GERMANY;

public class SimpleDomainPrompt {
    private final StringBuilder prompt = new StringBuilder();

    public SimpleDomainPrompt() {}

    /**
     * Method appends a standard prompt to the StringBuilder.
     * After that, other conditions can be added
     * @param fields The fields of the actual SimpleDomain class
     * @param location The language in which the prompt should be built.
     * @param numberOfEntities The number of values which should be generated by the gpt model.
     * @return The Prompt itself due to Fluent-Architecture
     */
    public SimpleDomainPrompt withMeta(Field[] fields, Locale location, int numberOfEntities) {
        if(location == GERMANY) {
            prompt.append("Generiere n=%d zufällige Werte für folgende m=%d Variablen:".formatted(numberOfEntities, fields.length)).append("\n");
            for(Field f : fields) prompt.append("- '").append(f.getName()).append("'").append("\n");
            prompt.append("Das Format der Ausgabe muss folgendermaßen sein:").append("\n");
            prompt.append("- Für die Variable i<=m: 'variable,wert1,wert2,wert3,wert4' und so weiter bis n.").append("\n");
            prompt.append("- Achte darauf, dass die generierten Werte keine Duplikate sind.").append("\n");

        } else {
            throw new UnsupportedLanguageException("%s is not supported".formatted(location.getCountry()));
        }
        return this;
    }

    /**
     * Appends another condition to the StringBuilder
     * @param condition Another condition
     * @return The Prompt itself due to Fluent-Architecture
     */
    public SimpleDomainPrompt withCondition(String condition) {
        prompt.append("- ").append(condition).append("\n");
        return this;
    }

    /**
     * Builds the prompt.
     * @return <code>String</code> The full prompt.
     */
    public String build() {
        prompt.append("Generiere auf keinen Fall anderen Output, außer wenn ein Fehler bei dir passiert: -1");
        return prompt.toString();
    }
}